#!/bin/sh

set -e -u

./services

mysql -u root -ppassword <<\____

    # Create the metasmoke database and metasmoke_test database

    CREATE DATABASE metasmoke;
    CREATE DATABASE metasmoke_test;
    CREATE DATABASE metasmoke_production;

    # Create the metasmoke user and password.
    # This user will only be able to access MySQL locally.
    # You should still select a strong password.
    # Grant this user privileges on the metasmoke database

    CREATE USER 'metasmoke'@'localhost' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON `metasmoke`.* TO `metasmoke`@`localhost`;
    GRANT ALL PRIVILEGES ON `metasmoke_test`.* TO `metasmoke`@`localhost`;
    GRANT ALL PRIVILEGES ON `metasmoke_production`.* TO `metasmoke`@`localhost`;
    FLUSH PRIVILEGES; 

____

sed '/^development:/!b;x;N;N;x;a\
  adapter: mysql2\
  database: metasmoke\
  encoding: utf8\
  username: metasmoke\
  password: password\
  host: 127.0.0.1\
  port: 3306
q' config/database.sample.yml >config/database.yml

sed 's/localhost/127.0.0.1/' config/config.sample.yml >config/config.yml
sed 's/localhost/127.0.0.1/' config/cable.sample.yml >config/cable.yml

rails db:create
rails db:schema:load
rails db:migrate
# rails db:seed

######## FIXME: yet another hard-coded, easily guessable password
rails c <<\____
u = User.create(
  username: 'metasmoke', email: 'metasmoke@localhost', password: 'password')
u.add_role(:admin)
u.add_role(:developer)

SiteSetting.create(name: 'registration_enabled', value: 1)

# Workaround for https://github.com/Charcoal-SE/metasmoke/issues/618
# https://github.com/Charcoal-SE/metasmoke/issues/887
SmokeDetector.create(
  last_ping: 1.hour.ago,
  name: 'Seed',
  location: 'Nowhere',
  access_token: '9b104345-ef52-41ce-86cc-003831e3a241',
  email_date: 1.hour.ago
)
____
