#!/bin/sh

set -e -u

service mariadb start

# Already handled by Procfile, but needed during bootstrapping
case "${1-}" in
 --no-redis) ;;
 *)
     ./redis-git/src/redis-server --port 6378 --loadmodule ./zhregex/module.so --dbfilename dump.rdb &
     ;;
esac
